name: main
description: "A new Flutter project."
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  firebase_auth: ^5.1.3
  country_picker: ^2.0.26
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  theme_provider: ^0.6.0
  cloud_firestore: ^5.2.1
  flutter_bloc: ^8.1.6
  sqflite: ^2.3.3+1
  sqflite_common_ffi: any
  path_provider: ^2.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  assets:
    - assets/images/logo.jpg
    - assets/images/google.jpeg
    - assets/images/facebook.png
    - assets/images/phone.png
    - assets/images/logo-homepage.png
  uses-material-design: true
