// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF7GwpZc9QaLuZaOhfeBYH9s-QCeDZq8g',
    appId: '1:197251247759:web:38460a1d54519d6bd88afa',
    messagingSenderId: '197251247759',
    projectId: 'authen-foodapp',
    authDomain: 'authen-foodapp.firebaseapp.com',
    storageBucket: 'authen-foodapp.appspot.com',
    measurementId: 'G-F6T74G2SSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMxJxiVWG8gSCdzpIxtDtOP4xM4nSnBt8',
    appId: '1:197251247759:android:c3418b63b629bd04d88afa',
    messagingSenderId: '197251247759',
    projectId: 'authen-foodapp',
    storageBucket: 'authen-foodapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Z5AaXzE2OrVo5vdZ85x-Cy-5D7DlIpg',
    appId: '1:197251247759:ios:0f3d70516f92265fd88afa',
    messagingSenderId: '197251247759',
    projectId: 'authen-foodapp',
    storageBucket: 'authen-foodapp.appspot.com',
    androidClientId: '197251247759-64ngu26il2rp0lhe03gcqgermr30lj03.apps.googleusercontent.com',
    iosClientId: '197251247759-dl3b5mqsv0kfe40j2utdtfgkd8cl5m6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.resApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Z5AaXzE2OrVo5vdZ85x-Cy-5D7DlIpg',
    appId: '1:197251247759:ios:0f3d70516f92265fd88afa',
    messagingSenderId: '197251247759',
    projectId: 'authen-foodapp',
    storageBucket: 'authen-foodapp.appspot.com',
    androidClientId: '197251247759-64ngu26il2rp0lhe03gcqgermr30lj03.apps.googleusercontent.com',
    iosClientId: '197251247759-dl3b5mqsv0kfe40j2utdtfgkd8cl5m6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.resApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF7GwpZc9QaLuZaOhfeBYH9s-QCeDZq8g',
    appId: '1:197251247759:web:adeb1623709279f8d88afa',
    messagingSenderId: '197251247759',
    projectId: 'authen-foodapp',
    authDomain: 'authen-foodapp.firebaseapp.com',
    storageBucket: 'authen-foodapp.appspot.com',
    measurementId: 'G-Y6NGPNEBYT',
  );
}
